name: mate_cli
description: A simple Flutter project for weather application.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  geolocator: ^10.0.0

  http: ^1.1.0

  flutter_dotenv: ^5.1.0

  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_app_name: ^0.1.1

flutter_app_name:
  name: "MateCli"

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
